"use strict";

/*
 * Company > Sites. NOT wired to any workflow yet (evidenceStatus:
 * "missing") — this file exists only to hold the fully evidenced
 * catalogs (Site Type, Site Status, Country) and known field selectors
 * so core/promptBuilder.js can ask Rovo for structured site data now,
 * and so a future workflow doesn't have to re-derive them.
 *
 * Open questions before this can go "ready":
 * - Does "Add New Site" open inline or in a separate browser window
 *   (like Industries/Verticals)?
 * - No before/after-save screenshot for #saveSiteInfoButton (starts
 *   disabled="disabled", same pattern as other confirmed Save buttons,
 *   but not yet confirmed for this one specifically).
 * - The separate "crawl link" feature (#addNewCrawlLink /
 *   crawlLinkSite{n} / crawlSaveButtonSite{n}) is a distinct sub-feature
 *   from this full site record form and is not represented here.
 */
(() => {
  const SITE_TYPE_OPTIONS = [
    { code: "1", label: "Primary HQ" },
    { code: "2", label: "Regional HQ" },
    { code: "3", label: "Regional Office" }
  ];

  const SITE_STATUS_OPTIONS = [
    { code: "1", label: "Current" },
    { code: "2", label: "Former" }
  ];

  const COUNTRY_OPTIONS = [
    { code: "1", label: "United States" },
    { code: "2", label: "United Kingdom" },
    { code: "5", label: "Canada" },
    { code: "105", label: "Afghanistan" },
    { code: "227", label: "Akrotiri and Dhekelia" },
    { code: "6", label: "Albania" },
    { code: "106", label: "Algeria" },
    { code: "107", label: "American Samoa" },
    { code: "108", label: "Andorra" },
    { code: "109", label: "Angola" },
    { code: "216", label: "Antigua" },
    { code: "222", label: "Anguilla" },
    { code: "7", label: "Argentina" },
    { code: "234", label: "Aruba" },
    { code: "8", label: "Armenia" },
    { code: "9", label: "Australia" },
    { code: "10", label: "Austria" },
    { code: "11", label: "Azerbaijan" },
    { code: "80", label: "Bahamas" },
    { code: "81", label: "Bahrain" },
    { code: "110", label: "Bangladesh" },
    { code: "217", label: "Barbados" },
    { code: "12", label: "Belarus" },
    { code: "13", label: "Belgium" },
    { code: "111", label: "Belize" },
    { code: "112", label: "Benin" },
    { code: "14", label: "Bermuda" },
    { code: "113", label: "Bhutan" },
    { code: "82", label: "Bolivia" },
    { code: "235", label: "Bonaire, Sint Eustatius and Saba" },
    { code: "15", label: "Bosnia-Herzegovina" },
    { code: "114", label: "Botswana" },
    { code: "16", label: "Brazil" },
    { code: "229", label: "British Indian Ocean Territory" },
    { code: "214", label: "British Virgin Islands" },
    { code: "115", label: "Brunei" },
    { code: "17", label: "Bulgaria" },
    { code: "116", label: "Burkina Faso" },
    { code: "117", label: "Burundi" },
    { code: "99", label: "Cambodia" },
    { code: "118", label: "Cameroon" },
    { code: "119", label: "Cape Verde" },
    { code: "83", label: "Cayman Islands" },
    { code: "120", label: "Central African Republic" },
    { code: "121", label: "Chad" },
    { code: "19", label: "Chile" },
    { code: "20", label: "China" },
    { code: "85", label: "Colombia" },
    { code: "123", label: "Comoros" },
    { code: "124", label: "Congo" },
    { code: "125", label: "Cook Islands" },
    { code: "86", label: "Costa Rica" },
    { code: "21", label: "Croatia" },
    { code: "236", label: "Cuba" },
    { code: "237", label: "Curacao" },
    { code: "22", label: "Cyprus" },
    { code: "23", label: "Czech Republic" },
    { code: "24", label: "Denmark" },
    { code: "238", label: "Dominica" },
    { code: "213", label: "Dominican Republic" },
    { code: "126", label: "Djibouti" },
    { code: "127", label: "East Timor" },
    { code: "104", label: "Ecuador" },
    { code: "25", label: "Egypt" },
    { code: "128", label: "El Salvador" },
    { code: "122", label: "Eritrea" },
    { code: "26", label: "Estonia" },
    { code: "129", label: "Ethiopia" },
    { code: "239", label: "Equatorial Guinea" },
    { code: "223", label: "Falkland Islands" },
    { code: "130", label: "Faroe islands" },
    { code: "98", label: "Fiji" },
    { code: "27", label: "Finland" },
    { code: "4", label: "France" },
    { code: "131", label: "French Polynesia" },
    { code: "240", label: "Gabon" },
    { code: "197", label: "Gambia" },
    { code: "132", label: "Gaza Strip" },
    { code: "28", label: "Georgia" },
    { code: "3", label: "Germany" },
    { code: "133", label: "Ghana" },
    { code: "230", label: "Gibraltar" },
    { code: "29", label: "Greece" },
    { code: "134", label: "Greenland" },
    { code: "218", label: "Grenada" },
    { code: "135", label: "Guatemala" },
    { code: "136", label: "Guinea" },
    { code: "137", label: "Guinea-Bissau" },
    { code: "138", label: "Guyana" },
    { code: "30", label: "Honduras" },
    { code: "233", label: "Haiti" },
    { code: "31", label: "Hong Kong" },
    { code: "32", label: "Hungary" },
    { code: "33", label: "Iceland" },
    { code: "34", label: "India" },
    { code: "35", label: "Indonesia" },
    { code: "139", label: "Iran" },
    { code: "140", label: "Iraq" },
    { code: "36", label: "Ireland" },
    { code: "37", label: "Israel" },
    { code: "38", label: "Italy" },
    { code: "141", label: "Ivory Coast" },
    { code: "87", label: "Jamaica" },
    { code: "39", label: "Japan" },
    { code: "40", label: "Jordan" },
    { code: "102", label: "Kazakhstan" },
    { code: "88", label: "Kenya" },
    { code: "142", label: "Kiribati" },
    { code: "232", label: "Kosovo" },
    { code: "42", label: "Kuwait" },
    { code: "143", label: "Kyrgyzstan" },
    { code: "144", label: "Laos" },
    { code: "43", label: "Latvia" },
    { code: "145", label: "Lebanon" },
    { code: "146", label: "Lesotho" },
    { code: "147", label: "Liberia" },
    { code: "44", label: "Liechtenstein" },
    { code: "45", label: "Lithuania" },
    { code: "46", label: "Luxembourg" },
    { code: "148", label: "Libya" },
    { code: "149", label: "Macao" },
    { code: "150", label: "Madagascar" },
    { code: "151", label: "Malawi" },
    { code: "48", label: "Malaysia" },
    { code: "152", label: "Maldives" },
    { code: "153", label: "Mali" },
    { code: "49", label: "Malta" },
    { code: "154", label: "Marshall Islands" },
    { code: "155", label: "Mauritania" },
    { code: "156", label: "Mauritius" },
    { code: "157", label: "Mayotte" },
    { code: "158", label: "Melanesia" },
    { code: "50", label: "Mexico" },
    { code: "159", label: "Micronesia" },
    { code: "51", label: "Moldova" },
    { code: "160", label: "Monaco" },
    { code: "161", label: "Mongolia" },
    { code: "162", label: "Montenegro" },
    { code: "224", label: "Montserrat" },
    { code: "52", label: "Morocco" },
    { code: "163", label: "Mozambique" },
    { code: "164", label: "Myanmar" },
    { code: "165", label: "Namibia" },
    { code: "166", label: "Nauru" },
    { code: "167", label: "Nepal" },
    { code: "53", label: "Netherlands" },
    { code: "168", label: "New Caledonia" },
    { code: "55", label: "New Zealand" },
    { code: "169", label: "Nicaragua" },
    { code: "170", label: "Niger" },
    { code: "103", label: "Nigeria" },
    { code: "171", label: "Niue" },
    { code: "172", label: "North Korea" },
    { code: "47", label: "North Macedonia" },
    { code: "173", label: "Northern Mariana Islands" },
    { code: "56", label: "Norway" },
    { code: "174", label: "Oman" },
    { code: "175", label: "Pakistan" },
    { code: "176", label: "Palau" },
    { code: "215", label: "Palestine" },
    { code: "101", label: "Panama" },
    { code: "89", label: "Papua New Guinea" },
    { code: "177", label: "Paraguay" },
    { code: "97", label: "Peru" },
    { code: "57", label: "Philippines" },
    { code: "178", label: "Pitcairn Islands" },
    { code: "58", label: "Poland" },
    { code: "179", label: "Polynesia" },
    { code: "59", label: "Portugal" },
    { code: "180", label: "Qatar" },
    { code: "181", label: "Reunion" },
    { code: "60", label: "Romania" },
    { code: "61", label: "Russia" },
    { code: "182", label: "Rwanda" },
    { code: "225", label: "Saint Helena" },
    { code: "219", label: "Saint Kitts and Nevis" },
    { code: "220", label: "Saint Lucia" },
    { code: "221", label: "Saint Vincent" },
    { code: "183", label: "Samoa" },
    { code: "62", label: "San Marino" },
    { code: "226", label: "Sandwich Islands" },
    { code: "241", label: "Sao Tome & Principe" },
    { code: "63", label: "Saudi Arabia" },
    { code: "185", label: "Senegal" },
    { code: "186", label: "Serbia" },
    { code: "187", label: "Seychelles" },
    { code: "188", label: "Sierra Leone" },
    { code: "65", label: "Singapore" },
    { code: "242", label: "Sint Maarten" },
    { code: "66", label: "Slovakia" },
    { code: "67", label: "Slovenia" },
    { code: "189", label: "Solomon Islands" },
    { code: "190", label: "Somalia" },
    { code: "68", label: "South Africa" },
    { code: "90", label: "South Korea" },
    { code: "69", label: "Spain" },
    { code: "191", label: "Sri Lanka" },
    { code: "192", label: "Sudan" },
    { code: "193", label: "Suriname" },
    { code: "194", label: "Swaziland" },
    { code: "70", label: "Sweden" },
    { code: "71", label: "Switzerland" },
    { code: "195", label: "Syria" },
    { code: "72", label: "Taiwan" },
    { code: "196", label: "Tajikistan" },
    { code: "100", label: "Tanzania" },
    { code: "73", label: "Thailand" },
    { code: "198", label: "Togo" },
    { code: "199", label: "Tokelau" },
    { code: "200", label: "Tonga" },
    { code: "231", label: "Trinidad and Tobago" },
    { code: "201", label: "Tunisia" },
    { code: "74", label: "Turkey" },
    { code: "202", label: "Turkmenistan" },
    { code: "228", label: "Turks and Caicos" },
    { code: "203", label: "Tuvalu" },
    { code: "204", label: "Uganda" },
    { code: "75", label: "Ukraine" },
    { code: "76", label: "United Arab Emirates" },
    { code: "91", label: "Uruguay" },
    { code: "205", label: "Uzbekistan" },
    { code: "206", label: "Vanuatu" },
    { code: "77", label: "Venezuela" },
    { code: "78", label: "Vietnam" },
    { code: "208", label: "Wallis and Futuna" },
    { code: "209", label: "West Bank" },
    { code: "243", label: "Western Sahara" },
    { code: "210", label: "Yemen" },
    { code: "211", label: "Zambia" },
    { code: "212", label: "Zimbabwe" }
  ];

  const ENTRY = {
    key: "company.sites",
    jsonPath: "company.sites",
    area: "Company",
    section: "Site",
    controlKind: "repeatableRecord",
    addButton: { candidates: ['[sid="addNewSite"]'] },
    form: {
      siteName: { candidates: ['input[name="site.siteName"]'] },
      siteType: { candidates: ['select[name="site.siteType.id"]'], options: SITE_TYPE_OPTIONS },
      address1: { candidates: ['input[name="site.address1"]'] },
      address2: { candidates: ['input[name="site.address2"]'] },
      city: { candidates: ['input[name="site.city"]'] },
      country: { candidates: ['select[name="site.countryCode.id"]'], options: COUNTRY_OPTIONS },
      province: { candidates: ['input[name="site.province"]'] },
      zip: { candidates: ['input[name="site.zip"]'] },
      phone: { candidates: ['input[name="site.phone"]'] },
      fax: { candidates: ['input[name="site.fax"]'] },
      email: { candidates: ['input[name="site.coEmailAddr"]'] },
      status: { candidates: ['select[name="site.siteStatus.id"]'], options: SITE_STATUS_OPTIONS }
    },
    saveButton: { scopedTo: "Company > Site", candidates: ["#saveSiteInfoButton"] },
    verification: { method: "disabledAfterSaveAndValueMatch" },
    duplicateRule: { normalize: "trim+collapseSpaces+lowercase", matchOn: ["address1", "city", "country"] },
    evidenceStatus: "missing",
    required: false
  };

  globalThis.SXRTS = globalThis.SXRTS || {};
  globalThis.SXRTS.registryEntries = globalThis.SXRTS.registryEntries || [];
  globalThis.SXRTS.registryEntries.push(ENTRY);
})();
